[tracking]
GA4_MEASUREMENT_ID = "G-XXXXXXX"
GA4_API_SECRET = "il_tuo_ga4_api_secret"
GA4_CLIENT_ID_FALLBACK = "forgialean-server"

FB_PIXEL_ID = "1234567890"
FB_ACCESS_TOKEN = "EAAB...."
FB_EVENT_SOURCE_URL = "https://www.tuodominio.it"