[tracking]
GA4_MEASUREMENT_ID = "G-XXXXXXX"
GA4_API_SECRET = "il_tuo_ga4_api_secret"
GA4_CLIENT_ID_FALLBACK = "forgialean-server"

FB_PIXEL_ID = "1234567890"
FB_ACCESS_TOKEN = "EAAB...."
FB_EVENT_SOURCE_URL = "https://www.tuodominio.it"
TELEGRAM_BOT_TOKEN = "7748973880:AAFy7qI-HC6ey2lX76iA6B3A4kc74gLf3yc"
TELEGRAM_CHAT_ID = "526530469"
[email]
SMTP_SERVER = "smtp.hostinger.com"
SMTP_PORT = 587
SMTP_USER = "info@forgialean.it"
SMTP_PASSWORD = "Guvidu_01"
FROM_ADDRESS = "info@forgialean.it"


